missions/week 5/back/ably/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.shortcuts import redirect

from contents.views import HomeView, ProductListView, ProductDetailView, SearchView, CategoryView, BrandView, CartView
from apis.views import KaKaoSignInView, KaKaoSignInCallBackView
from contents.pay_views import KaKaoPayLogic, KaKaoPayView, payFail, payCancel, PaySuccess


# NonUserTemplateView 를 사용하는 이유는 로그인과 회원가입 페이지에서 사용자의 접근을 막기위함
class NonUserTemplateView(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            return redirect('/')
        return super(NonUserTemplateView, self).dispatch(request, *args, **kwargs)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    # apis app urls.py connect
    path('apis/', include('apis.urls')),

    # product
    path('product/', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/category/<str:slug>/', CategoryView.as_view(), name='category_product_list'),
    path('product/brand/<str:slug>/', BrandView.as_view(), name='brand_product_list'),

    # cart
    path('cart/', CartView.as_view(), name='cart'),

    # search
    path('product/search/<str:q>/', SearchView.as_view(), name="search"),

    # user
    path('login/', NonUserTemplateView.as_view(template_name='user/login.html'), name='login'),
    path('register/', NonUserTemplateView.as_view(template_name='user/register.html'), name='register'),

    # kakao
    # path('user/login/kakao/', KaKaoSignInView.as_view(), name='kakao_login'),
    # path('user/login/kakao/callback/', KaKaoSignInCallBackView.as_view(), name='kakao_callback'),

    # 소셜로그인 관련 url
    # path('user/', include('allauth.urls')),
    path('social/', include('allauth.urls')),

    # 5주차
    # 카카오페이
    path('kakaoPay/', KaKaoPayView.as_view(), name='Pay'),
    path('kakaoPayLogic/', KaKaoPayLogic),
    path('payCancel/', payCancel),
    path('payFail/', payFail),
    path('paySuccsee/', PaySuccess),
]

missions/week 5/back/api/urls.py
from django.urls import include, path

from api import views

# django rest framework
from rest_framework import routers
from rest_framework_nested.routers import NestedSimpleRouter

router = routers.DefaultRouter()
router.register('product', views.ProductViewSet)

detail_router = NestedSimpleRouter(router, r'product', lookup='product')
detail_router.register(r'productdetail', views.ProductDetailViewSet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    path(r'', include(detail_router.urls)),
]

missions/week 5/back/back/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import validate_jwt_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

# 이미지를 업로드
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('product/', include('product.urls')),

    # JWT 관련
    path('validate/', validate_jwt_token),
    path('login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('verify/', TokenVerifyView.as_view()),

    path('user/', include('user.urls')),
]

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

missions/week 5/back/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as UserViews
from django.contrib.auth import views as auth_views

from manager.views import BlacklistTokenUpdateView, ManagerTokenObtainPairView
from seller.views import SellerTokenObtainPairView
from rest_framework_simplejwt.views import (
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # my_app
    path('', include('shop.urls')),
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('review/', include('review.urls')),

    # drf app
    path('api/manager/', include('manager.urls')),
    path('api/seller/', include('seller.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # drf jwt
    path('api/token-manager/', ManagerTokenObtainPairView.as_view(), name='token_obtain_pair_manager'),
    path('api/token-seller/', SellerTokenObtainPairView.as_view(), name='token_obtain_pair_seller'),

    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/logout/blacklist/', BlacklistTokenUpdateView.as_view(),name='blacklist'),

    # 소셜로그인
    path('accounts/', include('allauth.urls')),

    # 로그인
    path('login/', UserViews.login_form, name='login'),
    path('join/', UserViews.signup_form, name='join'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

missions/week 5/back/product/urls.py
from django.urls import include, path
from product import views

app_name = 'product'
urlpatterns = [
    path('', views.main, name='main'),
    path('search/', views.search, name='search'),
    path('<int:product_id>/detail/', views.detail, name='detail'),
    path('<int:product_id>/detail/write/', views.write, name='write'),
    path('<int:product_id>/detail/add_cart/', views.add_cart, name='add_cart'),
    path('cart/', views.cart, name='cart'),
    path('cart/detail_change/<int:detail_id>/', views.detail_change, name='detail_change'),
    path('cart/item_delete/<int:detail_id>/', views.item_delete, name='item_delete'),
    path('pay/', views.pay, name='pay'),
]

missions/week 5/back/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user import views

app_name = 'user'
urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('result/', views.result, name='result'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('login_by_kakao/', views.KakaoLogin, name='kakao_login'),
    path('connect/', views.kakao_connect, name='connect'),
]

missions/week 5/back/board/models.py
from django.db import models

# Create your models here.

class Board(models.Model):
    title = models.CharField(max_length=255, default='')
    type = models.CharField(max_length=15 , default='')
    content = models.TextField(null=True)
    private_yn = models.BooleanField(default=False)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

missions/week 5/back/cart/models.py
from operator import mod
from django.db import models
from mutbly.models import Item, Quantity
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

#### 문서보면서, cart html, model views 짜주는 중

class InCartItem(models.Model) :
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  item = models.ForeignKey(Item, null=True, on_delete=models.CASCADE, related_name='cart')
  quantity = models.IntegerField()
  # total_price = models.IntegerField(null=True)
  active = models.BooleanField(default=True)
  created_at = models.DateTimeField(default=timezone.now)
  
  def itemTotalPrice(self) :
    return self.item.price * self.quantity.quantity
  

  
  
  

missions/week 5/back/product/models.py
from django.db import models
from user.models import User
from shop.models import Shop


class Category(models.Model):
    category_id = models.CharField(max_length=10, primary_key=True)
    category_name = models.CharField(max_length=10)


class Product(models.Model):
    product_code = models.CharField(max_length=15)
    product_name = models.CharField(max_length=30)
    product_price = models.IntegerField(default=0)
    main_image = models.ImageField(null=True, upload_to="main_image/", blank=True)
    detail_image = models.ImageField(null=True, upload_to="detail_image/", blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default='None', db_column="category")
    shop_id = models.ForeignKey(Shop, on_delete=models.CASCADE, db_column="shop_id")


class ProductDetail(models.Model):
    color = models.CharField(max_length=20)
    size = models.CharField(max_length=10)
    stock = models.IntegerField()
    is_sold_out = models.BooleanField(default=False)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE, db_column="product_id", related_name='options')


class Board(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE, db_column="product_id")
    title = models.CharField(max_length=20, default='문의')
    content = models.CharField(max_length=200)
    comment = models.CharField(max_length=200, null=True)
    user_id = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default="알 수 없음", db_column="user_id")
    secret = models.BooleanField(default=False)
    date = models.DateTimeField(null=True, default=None)
    comment_date = models.DateTimeField(null=True, default=None)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, db_column="user")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, db_column="product")
    option = models.ForeignKey(ProductDetail, on_delete=models.CASCADE, db_column="product_detail")
    count = models.PositiveIntegerField()

missions/week 5/back/ABLY-externship-5/carts/forms.py
from django import forms


class AddMerchandiseForm(forms.Form):
    quantity = forms.IntegerField()
    is_updated = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

missions/week 5/back/board/forms.py
from bootstrap5 import models
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

RADIO_CHOICES = (("GOODS", "상품"), ("PAY", "결재"), ("REFUND", "환불"))


class BoardCreateForm(forms.Form):
    type = forms.ChoiceField(choices=RADIO_CHOICES, label="질문 유형", required=True)
    title = forms.CharField(required=True, max_length=100, label="제목")
    content = forms.CharField(widget=forms.Textarea, label="컨텐츠")

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

missions/week 5/back/carts/forms.py
from django import forms

from carts.models import Cart


class CartUpdateForm(forms.ModelForm):
    product = forms.CharField(max_length=14, disabled=True)

    class Meta:
        model = Cart
        fields = ['product', 'product_option', 'quantity']

missions/week 5/back/django_Ably/board/forms.py
from django import forms
from django.forms import widgets
# from .models import Board
# from django_summernote.fields import SummernoteTextField
# from django_summernote.widgets import SummernoteWidget

# class BoardWriteForm(forms.ModelForm):
#     title = forms.CharField(
#         label = '글 제목',
#         widget = forms.TextInput(
#             attrs={
#                 'placeholder': '게시글 제목'
#             }),
#         required=True,
#     )

#     contents = SummernoteTextField()

#     options = (
#         ('상품문의'),
#         ('반품문의'),
#         ('배송문의'),
#         ('기타')
#     )

#     board_name = forms.ChoiceField(
#         label = '선택',
#         widget = forms.Select(),
#         choices = options
#     )

#     field_order = [
#         'title',
#         'board_name',
#         'contents'
#     ]

#     class Meta:
#         model = Board
#         exclude = [
#             'title',
#             'contents',
#             'board_name'
#         ] 
#         widgets = {
#             'contents' : SummernoteWidget()
#         }
    
#     def clean(self):
#         cleaned_data = super().clean()

#         title = cleaned_data.get('title','')
#         contents = cleaned_data.get('contents','')
#         board_name = cleaned_data.get('board_name','')

#         if title =='':
#             self.add_error('title', '글 제목을 입력하세요.')
#         elif contents == '':
#             self.add_error('contents', '글 내용을 입력하세요.')
#         else:
#             self.title = title
#             self.contents = contents
#             self.board_name = board_name

from django.forms import ModelForm
from .models import *

class BoardForm(ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'content']

missions/week 5/back/mbly/product/forms.py
from django import forms
from product.models import Question, Answer

class ProductSearchForm(forms.Form):
    search_word = forms.CharField(label = 'Search Word')
    

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject','content'] # QuestionForm에서 사용할 QUestion 모델의 속성

        labels ={
            'subject':'제목',
            'content':'내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']

        labels = {
            'content':'내용',
        }

missions/week 5/back/product/forms.py
from django import forms
from django.forms import ModelForm
from product.models import Product, ProductOption


class ProductCreationForm(ModelForm):
    class Meta:
        model = Product
        fields = [
            'name',
            'price',
            'description',
            'image',
            'seller',
        ]


class ProductPurchaseForm(forms.Form):
    def __init__(self, product, *args, **kwargs):
        super().__init__(*args, **kwargs)

        options = ProductOption.objects.filter(product=product).order_by('size', 'color')
        choices = []
        for option in options:
            choices.append((option.id, f'{option.size}/{option.color}'))
        if not choices:
            choices = [(0, '재고없음')]

        self.fields['product_option'] = forms.ChoiceField(choices=choices)
        self.fields['product_option'].label = ''

missions/week 5/back/products/forms.py
from django import forms
from .models import Product
from inquirys.models import Inquiry


class RegisterForm(forms.Form):
    name = forms.CharField(
        error_messages={
            'required': '상품명을 입력해주세요.'
        }, label="상품명", max_length=64)

    price = forms.IntegerField(
        error_messages={
            'required': "상품 가격을 입력해주세요."
        }, label="상품 가격",
    )
    description = forms.CharField(
        error_messages={
            'required': "상품 설명을 입력해주세요."
        }, label="상품 설명"
    )
    quantity = forms.IntegerField(
        error_messages={
            'required': "재고를 입력해주세요."
        }, label="재고"
    )

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        price = cleaned_data.get('price')
        description = cleaned_data.get('description')
        quantity = cleaned_data.get('quantity')

        if not (name and price and description and quantity):
            self.add_error('quantity', '모든 값을 입력해야 합니다.')


class ProductSearchForm(forms.Form):
    kw = forms.CharField(label='keyword')


class InquiryForm(forms.ModelForm):

    class Meta:
        model = Inquiry
        fields = ['content']

missions/week 5/back/ABLY-externship-5/carts/views.py
from ast import Delete
from gc import get_objects
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from django.views.generic import RedirectView
from products.models import BaseMerchandise, Merchandise
from .forms import AddMerchandiseForm
from .cart import Cart

# Create your views here.


class CartAddView(RedirectView):
    
    def post(self, request, pk, *args, **kwargs):
        merchandise = get_object_or_404(Merchandise, id=pk)
        form = AddMerchandiseForm(request.POST)
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            is_updated = form.cleaned_data['is_updated']
            Cart(request).add(
                merchandise=merchandise,
                quantity=quantity,
                is_updated=is_updated
            )
        return redirect(f'http://127.0.0.1:8000/products/detail/{merchandise.basemerchandise}')


class CartUpdateView(View):
    
    def post(self, request, pk, *args, **kwargs):
        form = AddMerchandiseForm(request.POST)
        quantity = str(form['quantity'].value())
        merchandise = get_object_or_404(Merchandise, id=pk)
        Cart(request).update(str(merchandise), quantity)
        
        return redirect('cart_detail')


class CartDeleteView(View):
    
    def post(self, request, pk, *args, **kwargs):
        
        merchandise = get_object_or_404(Merchandise, id=pk)
        Cart(request).delete(str(merchandise))
        
        return redirect('cart_detail')


class CartClearView(View):
    
    def post(self, request, *args, **kwargs):
        
        Cart(request).clear()
        context = {
            'cart': Cart(request)
        }
        return render(request, 'carts/cart.html', context)


class CartDetailView(View):
    
    def get(self, request, *args, **kwargs):
        
        for merchandise in Cart(request):
            merchandise['quantity_form'] = AddMerchandiseForm(
                initial={
                    'quantity': merchandise['quantity'],
                    'is_updated': True
                }
            )
        context = {
            'cart': Cart(request),
            'form': AddMerchandiseForm()
        }
        return render(request, 'carts/cart.html', context)

missions/week 5/back/product/templates/product/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Mutbly{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap" rel="stylesheet">

</head>
<style>
    body {
        font-family: 'Gowun Dodum', sans-serif;
    }
    a {
        text-decoration: None;
        color: black;
        font-size: 1rem;

    }
    #main-area {
        height: 60%;
    }
    {% block style %}
    {% endblock %}
</style>
<script>
    {% block script %}
    {% endblock %}
</script>
<body>
<div align="right">
    {% if request.session.user is not None %}
        <span> {{ request.session.user_name }} 님 반갑습니다!</span>
        <a href="{% url 'user:logout' %}">로그아웃</a>
        <a href="{% url 'product:cart' %}">장바구니</a>
    {% else %}
        <a href="{% url 'user:login' %}">로그인</a>
        <a href="{% url 'user:signup' %}">회원가입</a>
    {% endif %}

</div>
<div class="header" style="width:100%; height: 25%; background-color:pink; text-align:center;">
    <a href="{% url 'product:main' %}" style="font-size:5em;">Mutbly</a>
</div>
<hr>
<div id="main-area">
    {% block content %}
    {% endblock %}
</div>

<hr>
{% include 'product/footer.html' %}

</body>
</html>

missions/week 5/back/product/templates/product/board.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        div.content {
            display: none;
            margin-top: 10px;
            padding: 20px;
            background-color: #faebf5;
        }
        form {
            display: inline-block;
            width: 85%;
            margin: 0 auto;
            text-align: center;
        }
        span.date {
            display: inline-block;
            float: right;
        }
    </style>
    <script>
        function divOnOff(element) {
            var panel = element.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        };

        function secretCheck(element) {
            var userid = "{{ request.session.user }}";
            var writerid = element.name;

            if (writerid == userid ) {
                divOnOff(element)
            } else {
                alert("작성자만 볼 수 있습니다.");
            }
        };
    </script>
</head>
<body>
<div class="container">
<form method="POST" action="{% url 'product:write' product.id %}">
    {% csrf_token %}
    <input class="form-control m-2" type="text" name='title' placeholder="제목" style="width:80%; margin:auto;" required>
    <textarea class="form-control m-2" rows='3' name='content' placeholder="내용" style="width:80%; margin:auto;" required></textarea>
    <input type="checkbox" name="secret" value=True>비밀글
    <input type="submit" value="등록">
</form>
{{ message }}
<br>
<br>
<div class="container">
<ul class="list-group list-group-flush">
    {% for item in board_list %}
        {% if item.secret %}
            <li class="list-group-item">
                <a href="javascript:void(0);" class="test" name="{{ item.user_id }}" onclick="secretCheck(this);">
                <span>비밀글입니다.</span>
                <span class="date" style="display:inline-block; float:right;">{{ item.user_id.user_name|slice:":2" }}*님&nbsp;&nbsp;|&nbsp;&nbsp;{{ item.date | date:"y-m-d H:i" }}</span>
                </a>
                <div class="content"><p>{{ item.content }}</p>
                    {% if item.comment %}
                        <hr>
                        <p>▶ {{ item.comment }}</p>
                    {% endif %}
                </div>
            </li>
        {% else %}
            <li class="list-group-item">
                <a href="javascript:void(0);" class="test" name="{{ item.user_id }}" onclick="divOnOff(this);">
                <span>{{ item.title }}</span>
                <span class="date" style="display:inline-block; float:right;">{{ item.user_id.user_name|slice:":2" }}*님&nbsp;&nbsp;|&nbsp;&nbsp;{{ item.date | date:"y-m-d H:i" }}</span>
                </a>
                <div class="content"><p>{{ item.content }}</p>
                    {% if item.comment %}
                        <hr>
                        <p>▶ {{ item.comment }}</p>
                    {% endif %}
                </div>
            </li>

    {% endif %}
    {% endfor %}

</ul>
</div>
</div>
</body>
</html>

missions/week 5/back/product/templates/product/cart.html
{% extends 'product/base.html' %}
{% load static %}
{% block style %}
    image {
        max-width: 90%;
        height: auto;
        object-fit: cover;
    }

    #total {
        font-size: 3rem;

    }

{% endblock %}
{% block script %}
        // 클릭시 숨겨놓은 항목 보여주기
        function divOnOff(element) {
            var panel = element.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        };

        function count(type)  {
          // 결과를 표시할 element
          const resultElement = document.getElementById('result');

          // 현재 화면에 표시된 값
          // let number = resultElement.innerText;
          let number = resultElement.value;

          // 더하기/빼기
          if(type === 'plus') {
              if(parseInt(number) === 999) {
                number = 999;
                alert('최대 수량을 초과하셨습니다.');
                }
                else{
                number = parseInt(number) + 1;
                }
          }else if(type === 'minus')  {
          if(parseInt(number) === 1) {
            alert('최소 수량입니다.');
            number = 1;
            }
            else{
            number = parseInt(number) - 1;
            }
          }

          // 결과 출력
          //resultElement.innerText = number;
          resultElement.value = number;
        }
{% endblock %}
{% block content %}
<h2 class="text-center">장바구니 목록</h2>
<div class="container">
    {% if message %}
        <h1 class="text-center">{{ message }}</h1>
    {% else %}
    <div class="row">
        <div class="col-sm-12 col-md-8">
        {% for item in product_list %}
            <div class="row g-0 border rounded overflow-hidden flex-md-row m-4 shadow-sm h-md-250 position-relative">
            <div class="col-auto d-lg-block m-3">
              <image class="bd-placeholder-img" width="200" height="250" src="{{ item.main_image.url }}" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></image>
            </div>
              <div class="col p-4 d-flex flex-column position-static">
              <strong class="d-inline-block mb-2 text-success">{{ item.product.shop_id.shop_name }}</strong>
              <h3 class="mb-0">{{ item.product.product_name }}</h3>
              <h4 class="mb-auto">{{ item.product.product_price }}</h4>
              <hr>
              <div class="mb-1 text-muted">옵션&nbsp;:&nbsp;{{ item.option.color }}&nbsp;{{ item.option.size }} &nbsp;</div>
              <div class="mb-1 text-muted">수량&nbsp;:&nbsp;{{ item.count }}&nbsp;개</div>
              <a href="{% url 'product:item_delete' item.id %}">삭제</a>
              <a href="javascript:void(0);" name="{{ item.user }}" onclick="divOnOff(this);">옵션 변경</a>
              <div class="mb-3" style="display: none;">
                  <form method="POST" action="{% url 'product:detail_change' item.id %}">
                    {% csrf_token %}
                    <span> 옵션 :</span>
                    <select class="form-select" name="option">
                        <option value="default" selected>---선택---</option>
                        {% for option in item.product.productdetail_set.all %}
                            <option value="{{ option.id }}" {% if option.stock == 0 %}disabled{% endif %}>{{ option.color }} {{ option.size }}  남은수량: {{ option.stock }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <span> 수량 :</span>
                    <input type='button' class="btn btn-outline-dark" onclick='count("minus")' value='-'/>
                    <input type='text' class="form-control w-50 d-inline-block" id='result' name="cnt" value="{{ item.count }}" />
                    <input type='button' class="btn btn-outline-dark" onclick='count("plus")' value='+'/>
                    <input type="submit" value="옵션 변경">
                  </form>

              </div>

            </div>

          </div>
        {% endfor %}
        </div>
        <div class="col-sm-12 col-md-4 p-3">
            <h3> 결제 금액</h3>
            <hr>
            <span id="total">{{ total }}</span><span>원</span><br>
            <button class="btn btn-outline-dark">결제하기</button>
        </div>
    {% endif %}
</div>
</div>
{% endblock %}

missions/week 5/back/product/templates/product/main.html
{% extends 'product/base.html' %}
{% load static %}
{% block content %}
<form method="POST" action="{% url 'product:search' %}">
    {% csrf_token %}
    <div class="container">
        <div class="row" style="width:100%">
            <div class="col-3">
                <select class="form-select" name="classification">
                    <option value="product" selected>상품</option>
                    <option value="brand">브랜드</option>
                </select>
            </div>
            <div class="col-7">
                <input class="form-control" type="text" placeholder="검색어를 입력해주세요" name="search_word">
            </div>
            <div class="col-2">
                <input type="submit" value="검색">
            </div>
        </div>
    </div>
</form>

<br>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
        {% for item in product_list %}
            <div class="col">
              <div class="card shadow-sm">
                <image src="{{ item.main_image.url }}"></image>

                <div class="card-body">
                  <span class="cost"> {{ item.product_price }}</span><br>
                  <span class="shop_name">{{ item.shop_id.shop_name }}</span><br>
                  <span class="product_name"><a href="{% url 'product:detail' item.id %}">{{ item.product_name }}</a></span>
                </div>
              </div>
            </div>
        {% endfor %}
    </div>
</div>

<!--Pagination-->
<div style="text-align:center">
    <div class="pagination">
        <div style="width:30%; margin:5px auto;">
            {% for page in product_list.paginator.page_range %}
                {% if page == product_list.number %}
                    <span style="font-weight:bold;">{{ page }}</span>
                {% else %}
                    <a href="?page={{ page }}">{{ page }}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}