missions/week 5/back/ably/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.shortcuts import redirect

from contents.views import HomeView, ProductListView, ProductDetailView, SearchView, CategoryView, BrandView, CartView
from apis.views import KaKaoSignInView, KaKaoSignInCallBackView
from contents.pay_views import KaKaoPayLogic, KaKaoPayView, payFail, payCancel, PaySuccess


# NonUserTemplateView 를 사용하는 이유는 로그인과 회원가입 페이지에서 사용자의 접근을 막기위함
class NonUserTemplateView(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            return redirect('/')
        return super(NonUserTemplateView, self).dispatch(request, *args, **kwargs)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    # apis app urls.py connect
    path('apis/', include('apis.urls')),

    # product
    path('product/', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/category/<str:slug>/', CategoryView.as_view(), name='category_product_list'),
    path('product/brand/<str:slug>/', BrandView.as_view(), name='brand_product_list'),

    # cart
    path('cart/', CartView.as_view(), name='cart'),

    # search
    path('product/search/<str:q>/', SearchView.as_view(), name="search"),

    # user
    path('login/', NonUserTemplateView.as_view(template_name='user/login.html'), name='login'),
    path('register/', NonUserTemplateView.as_view(template_name='user/register.html'), name='register'),

    # kakao
    # path('user/login/kakao/', KaKaoSignInView.as_view(), name='kakao_login'),
    # path('user/login/kakao/callback/', KaKaoSignInCallBackView.as_view(), name='kakao_callback'),

    # 소셜로그인 관련 url
    # path('user/', include('allauth.urls')),
    path('social/', include('allauth.urls')),

    # 5주차
    # 카카오페이
    path('kakaoPay/', KaKaoPayView.as_view(), name='Pay'),
    path('kakaoPayLogic/', KaKaoPayLogic),
    path('payCancel/', payCancel),
    path('payFail/', payFail),
    path('paySuccsee/', PaySuccess),
]

missions/week 5/back/account/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from account.views import (
    AccountCreateView,
    find_username_view,
    reset_password_view,
    change_password_view, oauth, kakao_login_view,
)
from rest_framework_jwt.views import (
    obtain_jwt_token,
    refresh_jwt_token,
    verify_jwt_token,
)

app_name = "account"

urlpatterns = [
    path('signup/', AccountCreateView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('kakao_login/', kakao_login_view, name='kakao_login'),
    path('oauth/', oauth, name='oauth'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('find_username/', find_username_view, name='find_username'),
    path('reset_password/', reset_password_view, name='reset_password'),
    path('change_password/', change_password_view, name='change_password'),

    path('token/', obtain_jwt_token),
    path('token/refresh/', refresh_jwt_token),
    path('token/verify/', verify_jwt_token), # 검증

]

missions/week 5/back/accounts/urls.py
from django.urls import path, include
from accounts import views
from django.contrib.auth import views as auth_views
from rest_framework.authtoken.views import obtain_auth_token


app_name= 'accounts'

urlpatterns = [
  path('', include('django.contrib.auth.urls')),
  path('signup/', views.signup, name='signup'),
  path('login/', auth_views.LoginView.as_view(), name='login'),
  path('forgot_id/', views.forgot_id, name='find_id'),
  path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
  # path('social_accounts/', include('allauth.urls')),
  path('api/token/', obtain_auth_token, name='obtain_token'),
]

missions/week 5/back/api/urls.py
from django.urls import include, path

from api import views

# django rest framework
from rest_framework import routers
from rest_framework_nested.routers import NestedSimpleRouter

router = routers.DefaultRouter()
router.register('product', views.ProductViewSet)

detail_router = NestedSimpleRouter(router, r'product', lookup='product')
detail_router.register(r'productdetail', views.ProductDetailViewSet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    path(r'', include(detail_router.urls)),
]

missions/week 5/back/back/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import validate_jwt_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

# 이미지를 업로드
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('product/', include('product.urls')),

    # JWT 관련
    path('validate/', validate_jwt_token),
    path('login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('verify/', TokenVerifyView.as_view()),

    path('user/', include('user.urls')),
]

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

missions/week 5/back/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as UserViews
from django.contrib.auth import views as auth_views

from manager.views import BlacklistTokenUpdateView, ManagerTokenObtainPairView
from seller.views import SellerTokenObtainPairView
from rest_framework_simplejwt.views import (
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # my_app
    path('', include('shop.urls')),
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('review/', include('review.urls')),

    # drf app
    path('api/manager/', include('manager.urls')),
    path('api/seller/', include('seller.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # drf jwt
    path('api/token-manager/', ManagerTokenObtainPairView.as_view(), name='token_obtain_pair_manager'),
    path('api/token-seller/', SellerTokenObtainPairView.as_view(), name='token_obtain_pair_seller'),

    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/logout/blacklist/', BlacklistTokenUpdateView.as_view(),name='blacklist'),

    # 소셜로그인
    path('accounts/', include('allauth.urls')),

    # 로그인
    path('login/', UserViews.login_form, name='login'),
    path('join/', UserViews.signup_form, name='join'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

missions/week 5/back/mutbly/urls.py
from django.contrib import admin
from django.urls import path, include
import mutbly.views
import accounts.views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', mutbly.views.index, name='index'),
    
     #user
    path('accounts/', include('accounts.urls', namespace= 'accounts')), 
    path('social_accounts/', include('allauth.urls')),
    
    #apis app
    path('apis/', include('apis.urls', namespace = "apis")),
    
    #search
    path('search/', mutbly.views.search, name='search'),
    
    #product
    path('items/<int:id>/', mutbly.views.show, name = 'show'),
    path('items/<int:id>/questions/', mutbly.views.QuestionView.create, name='question_create'),
    path('items/<int:id>/questions/<int:cid>', mutbly.views.QuestionView.delete, name='question_delete'),   
]

#image
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

missions/week 5/back/mbly/account/models.py
from typing import AbstractSet
from django.db import models

# Create your models here.

missions/week 5/back/accounts/forms.py
from django import forms

from .models import *


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['name', 'address', 'postal_code', 'extra_address', 'phone']

missions/week 5/back/mbly/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label = '이메일')

    class Meta:
        model = User
        fields = ("username","password1","password2","email")

missions/week 5/back/account/api/views.py
from django.contrib.auth import login, logout, authenticate
from rest_framework import status, generics
from rest_framework.views import APIView
from rest_framework.response import Response
from account.api.serializers import SignupUserSerializer, ChangePasswordSerializer
from account.models import User


class SignupUserView(APIView):
    def post(self, request):
        serializer = SignupUserSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        username = serializer.validated_data['username']
        if User.objects.filter(username=username).exists():
            return Response(data={'error': '이미 존재하는 username 입니다.'}, status=status.HTTP_401_UNAUTHORIZED)

        User.objects.create_user(username=username, email=serializer.validated_data['email'],
                                 password=serializer.validated_data['password'])
        return Response(serializer.data, status=status.HTTP_201_CREATED)


class LoginView(APIView):
    def post(self, request):

        user = authenticate(username=request.data['username'], password=request.data['password'])

        if user is not None:
            if user.is_active:
                login(request, user)
                return Response(status=status.HTTP_200_OK)
            else:
                return Response(status=status.HTTP_401_UNAUTHORIZED)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)


class LogoutView(APIView):
    def post(self, request):
        logout(request)

        return Response(status=status.HTTP_200_OK)


class ChangePasswordView(generics.UpdateAPIView):
    queryset = User.objects.all()
    serializer_class = ChangePasswordSerializer

missions/week 5/back/account/views.py
import secrets
import requests
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from account.forms import AccountCreateForm, FindusernameForm, ResetpasswordForm, ChangePasswordForm
from account.models import User
from django.shortcuts import redirect


class AccountCreateView(CreateView):
    model = User
    form_class = AccountCreateForm
    success_url = reverse_lazy('base')
    template_name = 'account/signup.html'


def find_username_view(request):
    if request.method == 'GET':
        return render(
            request,
            'account/find_username.html',
            context={
                'form': FindusernameForm(),
            }
        )

    elif request.method == 'POST':
        # email 로 아이디 찾기
        form = FindusernameForm(request.POST)
        if form.is_valid():
            target_email = form.cleaned_data['email']
            try:
                find_user = User.objects.get(email=target_email)
            except User.DoesNotExist:
                messages.info(request, '입력한 이메일에 해당하는 유저가 없습니다.')
                return redirect(request.META['HTTP_REFERER'])

            # 이메일 발송
            subject = '멋블리 아이디 찾기 결과 안내'
            content = '안녕하세요.' \
                      '아이디 찾기 결과 입니다.' \
                      f'아이디는 {find_user.username} 입니다.' \
                      '감사합니다.'

            send_mail(
                subject,
                content,
                'min949494@gmail.com',
                [
                    target_email,
                ],
                fail_silently=True,
            )
            return render(
                request,
                'account/find_username_form_result.html',
                context={
                    'target_email': target_email,
                }
            )


def reset_password_view(request):
    if request.method == 'GET':
        return render(request,
                      'account/reset_password.html',
                      context={
                          'form': ResetpasswordForm(),
                      }
                      )
    elif request.method == 'POST':
        form = ResetpasswordForm(request.POST)
        if form.is_valid():
            target_email = form.cleaned_data['email']
            try:
                find_user = User.objects.get(email=target_email)
            except User.DoesNotExist:
                messages.info(request, '입력한 이메일에 해당하는 유저가 없습니다.')
                return redirect(request.META['HTTP_REFERER'])

            token = secrets.token_urlsafe()
            find_user.tmp_token = token
            find_user.save()

            # 1회성 패스워드 리셋 URL
            url = f'http://127.0.0.1:8000/accounts/change_password/?reset_token={token}'

            subject = '비밀번호 재설정 이메일 입니다.'
            content = '안녕하세요.' \
                      '비밀번호 변경 URL 입니다.' \
                      f'URL : {url}'

            send_mail(
                subject,
                content,
                'min949494@gmail.com',
                [
                    target_email,
                ],
                fail_silently=True,
            )
    return render(
        request,
        'account/reset_password_form_result.html',
        context={
            'target_email': target_email,
        }
    )


def change_password_view(request):
    if request.method == 'GET':
        token = request.GET.get('reset_token')

        try:
            user = User.objects.get(tmp_token=token)
        except User.DoesNotExist:
            return HttpResponse('잘못된 접근입니다.')

        return render(
            request,
            'account/change_password_form.html',
            context={
                'token': token,
                'user': user,
                'form': ChangePasswordForm()
            }
        )
    elif request.method == 'POST':
        token = request.POST.get('token')

        try:
            user = User.objects.get(tmp_token=token)
        except User.DoesNotExist:
            return HttpResponse('잘못된 접근입니다.')

        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            user.set_password(form.cleaned_data['password1'])
        else:
            messages.info(request, '비밀번호 변경, 확인이 서로 다릅니다.')
            return redirect(request.META['HTTP_REFERER'])
        user.tmp_token = None
        user.save()

        return redirect('product:list')


def oauth(request):
    code = request.GET['code']
    print('code = ' + str(code))

    client_id = 'a37a43d7902878faaba209dbe6cee083'
    redirect_uri = 'http://127.0.0.1:8000/oauth'

    access_token_request_uri = 'https://kauth.kakao.com/oauth/token?grant_type=authorization_code&'

    access_token_request_uri += 'client_id=' + client_id
    access_token_request_uri += '&redirect_uri=' + redirect_uri
    access_token_request_uri += '&code=' + code

    print(access_token_request_uri)

    access_token_request_uri_data = requests.get(access_token_request_uri)
    json_data = access_token_request_uri_data.json()
    access_token = json_data['access_token']

    print('access_token = ' + str(access_token))

    user_profile_info_uri = 'https://kapi.kakao.com/v2/user/me?access_token='
    user_profile_info_uri += str(access_token)
    print(user_profile_info_uri)

    user_profile_info_uri_data = requests.get(user_profile_info_uri)
    user_json_data = user_profile_info_uri_data.json()
    user_email = user_json_data['kakao_account']['email']
    user_nickname = user_json_data['kakao_account']['profile']['nickname']
    print(user_nickname)
    print(user_email)

    try:
        user = User.objects.get(email=user_email)

    except User.DoesNotExist:
        user = User.objects.create_user(username=user_nickname, email=user_email)
        user.save()
    auth_login(request, user, backend='django.contrib.auth.backends.ModelBackend')
    return redirect('base')


def kakao_login_view(request):
    login_request_uri = 'https://kauth.kakao.com/oauth/authorize?'

    client_id = 'a37a43d7902878faaba209dbe6cee083'
    redirect_uri = 'http://127.0.0.1:8000/oauth'

    login_request_uri += 'client_id=' + client_id
    login_request_uri += '&redirect_uri=' + redirect_uri
    login_request_uri += '&response_type=code'

    return redirect(login_request_uri)

missions/week 5/back/mbly/account/api/views.py
from rest_framework.generics import ListAPIView
from rest_framework.views import APIView
from django.contrib.auth.models import User
from .serializers import UserSerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from market.models import Market

class UserInfoView(APIView):
    """
    사용자 정보 출력
    """
    permission_classes = [IsAuthenticated]

    def get(self,request):
        user = User.objects.get(pk = request.user.id)
        market = Market.objects.filter(master = user)
        serializer = UserSerializer(user)
        return Response(serializer.data)

missions/week 5/back/accounts/templates/accounts/find_id.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Mutbly</title>
  </head>
  <body>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
  
    <br/>
    <h1 style ="max-width:480px;margin:auto;"> 아이디 찾기 </h1>
    <br/>
    <p style ="max-width:480px;margin:auto;">회원가입 시 사용하신 이메일을 입력해주세요</p>
    <br/>

    <span> 
        <div class="login-form" style ="max-width:480px;margin:auto;">
        <form class="form-group" method="POST" action="{% url 'find_id' %}">
            {% csrf_token %}
            <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" name="email" class="form-control"  placeholder="Email">
            {% for message in messages  %}
              {{message}}
            {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary">아이디 찾기</button>
        </form>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href={% url 'signup' %}>회원가입</a>
        <a class="dropdown-item" href={% url 'login' %}>로그인</a>
        <a class="dropdown-item" href={% url 'password_reset' %}>비밀번호 찾기</a>
        </div>
    </span>


  </body>
</html>

missions/week 5/back/accounts/templates/accounts/profile.html
{% extends 'common/base.html' %}
{% block title %}{{ user.username }}님 - 멋블리{% endblock %}
{% load django_bootstrap5 %}
{% block content %}
    <h4>{{ user.username }}님</h4>
    <p><a href="{% url 'list' %}">주문 목록</a></p>
    <p><a class="btn btn-danger" href="{% url 'logout' %}">로그아웃</a></p>
{% endblock %}

missions/week 5/back/accounts/templates/accounts/recovery.html
{% extends 'common/base.html' %}
{% block title %}아이디 찾기 - 멋블리{% endblock %}
{% load django_bootstrap5 %}
{% block content %}
    <h4>아이디 찾기</h4>
    <form method="post" action="{% url 'recovery_done' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="계정 찾기" %}
    </form>
    <p><a href="{% url 'login' %}">로그인</a></p>
{% endblock %}

missions/week 5/back/accounts/templates/accounts/register.html
{% extends 'common/base.html' %}
{% block title %}회원 가입 - 멋블리{% endblock %}
{% load django_bootstrap5 %}
{% block content %}
    <h4>회원 가입</h4>
    <form method="post" action="{% url 'register_succeeded' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="회원 가입" %}
    </form>
    <p><a href="{% url 'login' %}">로그인</a></p>
{% endblock %}

missions/week 5/back/accounts/templates/accounts/register_succeeded.html
{% extends 'common/base.html' %}
{% block title %}회원 가입 완료 - 멋블리{% endblock %}
{% load django_bootstrap5 %}
{% block content %}
    <h4>회원 가입 완료</h4>
    <p>{{ username }}님, 회원 가입 완료!</p>
{% endblock %}

missions/week 5/back/accounts/templates/accounts/signup.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Mutbly</title>
  </head>
  <body>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
   
    <br/>
    <h1 style ="max-width:480px;margin:auto;"> 회원가입 </h1>
    <br/>
    <br/>

    <span> 
        <div class="login-form" style ="max-width:480px;margin:auto;">
        <form class="form-group" method="POST" action="{%url 'accounts:signup' %}">
            {% csrf_token %}
            <div class="mb-3">
            <label for="id" class="form-label">ID</label>
            <input type="text" name="username" class="form-control"  placeholder="ID">
            </div>
            <div class="mb-3">
              <label for="id" class="form-label">Email</label>
              <input type="email" name="email" class="form-control"  placeholder="Email">
              </div>
            <div class="mb-3">
            <label for="Password1" class="form-label">PW</label>
            <input type="password" name="password1" class="form-control" id="Password" placeholder="Password">
            </div>
            <div class="mb-3">
              <label for="Password2" class="form-label">PW Check</label>
              <input type="password" name="password2" class="form-control" id="Password" placeholder="Password Chack">
              </div>
            <div class="mb-3">
            <div class="form-check">

            </div>
            </div>
            <button type="submit" class="btn btn-primary">회원가입</button>
        </form>
        <div class="dropdown-divider"></div>
            <div class="mb-3">
        <a class="dropdown-item" href={% url 'accounts:login' %}>로그인</a>
        <a class="dropdown-item" href={% url 'accounts:find_id' %}>아이디 찾기</a>
        <a class="dropdown-item" href={% url 'accounts:password_reset' %}>비밀번호 찾기</a>
        </div>
    </span>


  </body>
</html>