missions/week 5/back/ably/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.shortcuts import redirect

from contents.views import HomeView, ProductListView, ProductDetailView, SearchView, CategoryView, BrandView, CartView
from apis.views import KaKaoSignInView, KaKaoSignInCallBackView
from contents.pay_views import KaKaoPayLogic, KaKaoPayView, payFail, payCancel, PaySuccess


# NonUserTemplateView 를 사용하는 이유는 로그인과 회원가입 페이지에서 사용자의 접근을 막기위함
class NonUserTemplateView(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            return redirect('/')
        return super(NonUserTemplateView, self).dispatch(request, *args, **kwargs)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    # apis app urls.py connect
    path('apis/', include('apis.urls')),

    # product
    path('product/', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/category/<str:slug>/', CategoryView.as_view(), name='category_product_list'),
    path('product/brand/<str:slug>/', BrandView.as_view(), name='brand_product_list'),

    # cart
    path('cart/', CartView.as_view(), name='cart'),

    # search
    path('product/search/<str:q>/', SearchView.as_view(), name="search"),

    # user
    path('login/', NonUserTemplateView.as_view(template_name='user/login.html'), name='login'),
    path('register/', NonUserTemplateView.as_view(template_name='user/register.html'), name='register'),

    # kakao
    # path('user/login/kakao/', KaKaoSignInView.as_view(), name='kakao_login'),
    # path('user/login/kakao/callback/', KaKaoSignInCallBackView.as_view(), name='kakao_callback'),

    # 소셜로그인 관련 url
    # path('user/', include('allauth.urls')),
    path('social/', include('allauth.urls')),

    # 5주차
    # 카카오페이
    path('kakaoPay/', KaKaoPayView.as_view(), name='Pay'),
    path('kakaoPayLogic/', KaKaoPayLogic),
    path('payCancel/', payCancel),
    path('payFail/', payFail),
    path('paySuccsee/', PaySuccess),
]

missions/week 5/back/api/urls.py
from django.urls import include, path

from api import views

# django rest framework
from rest_framework import routers
from rest_framework_nested.routers import NestedSimpleRouter

router = routers.DefaultRouter()
router.register('product', views.ProductViewSet)

detail_router = NestedSimpleRouter(router, r'product', lookup='product')
detail_router.register(r'productdetail', views.ProductDetailViewSet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    path(r'', include(detail_router.urls)),
]

missions/week 5/back/back/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import validate_jwt_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

# 이미지를 업로드
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('product/', include('product.urls')),

    # JWT 관련
    path('validate/', validate_jwt_token),
    path('login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('verify/', TokenVerifyView.as_view()),

    path('user/', include('user.urls')),
]

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

missions/week 5/back/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as UserViews
from django.contrib.auth import views as auth_views

from manager.views import BlacklistTokenUpdateView, ManagerTokenObtainPairView
from seller.views import SellerTokenObtainPairView
from rest_framework_simplejwt.views import (
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # my_app
    path('', include('shop.urls')),
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('review/', include('review.urls')),

    # drf app
    path('api/manager/', include('manager.urls')),
    path('api/seller/', include('seller.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # drf jwt
    path('api/token-manager/', ManagerTokenObtainPairView.as_view(), name='token_obtain_pair_manager'),
    path('api/token-seller/', SellerTokenObtainPairView.as_view(), name='token_obtain_pair_seller'),

    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/logout/blacklist/', BlacklistTokenUpdateView.as_view(),name='blacklist'),

    # 소셜로그인
    path('accounts/', include('allauth.urls')),

    # 로그인
    path('login/', UserViews.login_form, name='login'),
    path('join/', UserViews.signup_form, name='join'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

missions/week 5/back/cart/urls.py
from django.urls import path
import cart.views

app_name = 'cart'

urlpatterns = [
    path('', cart.views.show_cart, name='show_cart'),
    path('<int:id>/add_cart/', cart.views.add_cart, name='add_cart'),
    path('<int:id>/delete_cart/', cart.views.delete_cart, name='delete_cart'),
    path('<int:id>/update_cart/', cart.views.update_cart, name='update_cart'),
    
    
]

missions/week 5/back/review/urls.py
from django.urls import path
from .views import *

app_name = 'review'

urlpatterns = [
    path('<int:product_id>', review_list, name='review_list'),
    path('register/<int:product_id>', review_create, name="review_create"),
    path('detail/<int:review_id>', review_detail, name="review_detail"),
    path('modify/<int:review_id>', review_modify, name="review_modify"),
    path('remove/<int:review_id>', review_delete, name="review_delete"),
    path('reviewbot', use_reviewbot, name="review_bot"),

]

missions/week 5/back/django_Ably/Review/models.py
from django.db import models

class Review(models.Model):
    id_review = models.CharField(db_column='id_Review', primary_key=True, max_length=5)  # Field name made lowercase.
    title = models.CharField(max_length=100, blank=True, null=True)
    content = models.CharField(max_length=500, blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    auth_user = models.ForeignKey('accounts.AuthUser', models.DO_NOTHING)
    store_id_store = models.ForeignKey('markets.Store', models.DO_NOTHING, db_column='Store_id_Store')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Review'

missions/week 5/back/review/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User


# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=100, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=250,blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    violation = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class ReviewBot(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    use_bot = models.BooleanField(default=False)
    def __str__(self):
         return self.user.username

missions/week 5/back/review/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Review, ReviewBot
from shop.models import Product, Category, Inventory
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .classifier import mespredict
from .repeat import is_reapeated
from django.contrib import messages


@login_required(login_url='login')
def review_list(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    categories = Category.objects.all()
    inventories = Inventory.objects.filter(product=product.id)

    # 상품 문의 페이지네이터
    page = request.GET.get('page')
    reviews = Review.objects.filter(product=product.id)
    paginator = Paginator(reviews, 7)
    page_obj = paginator.get_page(page)

    context = {'product': product, 'categories': categories,
               'reviews': reviews, 'inventories': inventories,
               'page_obj': page_obj}
    return render(request, 'review/list.html', context)


# 리뷰 등록 -------
@login_required(login_url='login')
def review_create(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    context = {'product': product}
    if request.method == 'POST':
        comment = request.POST['body']
        predict = mespredict(comment)
        repeated = is_reapeated(comment)
        if predict == 0 and repeated == False:
            current_user = request.user
            title = request.POST['title']
            Review.objects.create(user_id=current_user.id,
                                    product_id=product_id,
                                    title=title,
                                    comment=comment,
                                    violation=False,
                                    )
            return redirect(reverse('review:review_list', kwargs={'product_id':product.id}))
        else:
            current_user = request.user
            title = request.POST['title']
            Review.objects.create(user_id=current_user.id,
                                    product_id=product_id,
                                    title=title,
                                    comment=comment,
                                    violation=True,
                                    )
            messages.warning(request, "해당 리뷰는 리뷰봇에 의해 필터링될 수 있습니다.")
            return redirect(reverse('review:review_list', kwargs={'product_id': product.id}))
    return render(request, 'review/create.html', context)


# 리뷰 디테일 -------
@login_required(login_url='login')
def review_detail(request, review_id):
    current_user = request.user
    bot_status = ReviewBot.objects.filter(user_id=current_user.id).exists()
    if bot_status == True:
        is_use_bot = ReviewBot.objects.get(user_id=current_user.id).use_bot
    else:
        is_use_bot = False
    review = get_object_or_404(Review, pk=review_id)
    product = get_object_or_404(Product, id=review.product_id)
    context = {'review': review, 'product': product, 'is_use_bot':is_use_bot}
    return render(request, 'review/detail.html', context)


# 리뷰 수정 -------
@login_required(login_url='login')
def review_modify(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    product = get_object_or_404(Product, id=review.product_id)
    context = {'product': product, 'review':review}

    if request.method == 'POST':
            review = get_object_or_404(Review, pk=review_id)
            title = request.POST['title']
            comment = request.POST['body']
            predict = mespredict(comment)
            repeat = is_reapeated(comment)
            if predict == 0 and repeat == False:
                review.user_id=review.user.id
                review.product_id=product.id
                review.title=title
                review.comment=comment
                review.violation = False
                review.save()
                return redirect(reverse('review:review_list', kwargs={'product_id':product.id}))
            else:
                review.user_id=review.user.id
                review.product_id=product.id
                review.title=title
                review.comment=comment
                review.violation = True
                review.save()
                messages.warning(request, "해당 리뷰는 리뷰봇에 의해 필터링될 수 있습니다.")
                return redirect(reverse('review:review_list', kwargs={'product_id':product.id}))
    return render(request, 'review/modify.html', context)



# 리뷰 삭제 -------
def review_delete(request, review_id):
    review = get_object_or_404(Review, pk=review_id)

    if request.user != review.user:
        # messages.warning(request, '삭제 권한이 없습니다.')
        return redirect((request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found')))
    else:
        review.delete()
        return redirect((request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found')))


# 봇 사용 상태 변경 -----
@login_required(login_url='login')
def use_reviewbot(request):
    usebot_exist = ReviewBot.objects.filter(user_id=request.user.id).exists()
    if usebot_exist ==True:
        bot_status = ReviewBot.objects.get(user_id=request.user.id)
    else:
        bot_status = False

    if request.method == 'POST':
        # 봇 사용 처음 등록할 시---
        if usebot_exist == False:
            select = False
            if request.POST['choice'] == "1":
                select = True
            ReviewBot.objects.create(user_id=request.user.id,
                                       use_bot=select
                                     )
            return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
        else:
            reviewbot = ReviewBot.objects.get(user_id=request.user.id)
            if request.POST['choice'] == "1":
                reviewbot.use_bot = True
                reviewbot.save()
                return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
            else:
                reviewbot.use_bot = False
                reviewbot.save()
                return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

    return render(request, 'review/reviewbot.html', {'bot_status':bot_status})

missions/week 5/back/templates/review/create.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}
<br>
<br>
<br>
<div class="row">
    <!--  장바구니 칸 시작  -->
    <div class="category_box" style="text-align:center;">
        <p style="padding-top:8px; padding-right:8px;"><b>리뷰 작성</b></p>
    </div>

    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div style="display:flex; margin-top:5px;">
            {% if product.image.url == True %}
            <a href="{{product.get_absolute_url}}"><img class="item_img" src="{{product.image.url}}"></a>
            {% else %}
            <a href="{{product.get_absolute_url}}"><img class="item_img" src="{{product.image_url}}"></a>
            {% endif %}
            <div style="margin-top:10px;">
                <div class="word" style ="padding-left:15px; width:220px; font-size:16px; color:gray;">
                    리뷰 상품: {{ product }}
                </div>
                <div style="font-size:16px; color:gray; padding-left:15px; padding-top:10px;">
                   가격: {{ product.price|intcomma }} KRW
                </div>
            </div>
        </div>
    </li>


    <!-- 리 입력란 시작   -->
    <div style="margin-left:20px; margin-top:20px; margin-bottom:150px; width:320px;">
        <form action="{% url 'review:review_create' product.id %}" method="POST">
        {% csrf_token %}
        <div class="mb-3" style="width:280px;">
          <label for="exampleFormControlInput1" class="form-label">제목</label>
          <input type="text" name='title' class="form-control" id="exampleFormControlInput1" placeholder="제목을 입력해주세요.">
        </div>
        <div class="mb-3" style="width:320px;">
          <label for="exampleFormControlTextarea1" class="form-label">리뷰 내용</label>
          <textarea name="body" style="height:250px;" class="form-control" id="exampleFormControlTextarea1" placeholder="리뷰 내용을 입력해주세요." rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-outline-secondary" style="margin-top:15px; margin-left:125px;">등록하기</button>
        </form>
    </div>
    <!-- 리뷰 입력란 끝 -->
</div>

{% endblock %}

missions/week 5/back/templates/review/detail.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}
<br>
<br>
<br>
<div class="row">
    <!--  장바구니 칸 시작  -->
    <div class="category_box" style="text-align:center;">
        <p style="padding-top:8px; padding-right:8px;"><b>리뷰 내용</b></p>
    </div>

    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div style="display:flex; margin-top:5px;">
            {% if product.image.url == True %}
            <a href="{{product.get_absolute_url}}"><img class="item_img" src="{{product.image.url}}"></a>
            {% else %}
            <a href="{{product.get_absolute_url}}"><img class="item_img" src="{{product.image_url}}"></a>
            {% endif %}
            <div style="margin-top:10px;">
                <div class="word" style ="padding-left:15px; width:220px; font-size:16px; color:gray;">
                    리뷰 상품: {{ product }}
                </div>
                <div style="font-size:16px; color:gray; padding-left:15px; padding-top:10px;">
                   가격: {{ product.price|intcomma }} KRW
                </div>
            </div>
        </div>
    </li>
    <div class="card" style="width: 20rem; margin-left:39px; height:auto; margin-top:50px;">
      <div class="card-body" style="margin-bottom:25px; margin-top:20px;">
        <h3 class="card-title">{{review.title}}</h3>
        <div>
            <h6 class="card-subtitle mb-2 text-muted" style="font-size:13px; margin-top:10px;">{{review.user}} | {{review.create_at | date:"Y.m.d"}}</h6>
        </div>
        <div style="margin-top:25px;">
            {% if is_use_bot and review.violation == True %}
                <p class="card-text">리뷰봇에 의해 숨겨진 리뷰입니다 🤖</p>
            {% else %}
                <p class="card-text">{{review.comment}}</p>
            {% endif %}
        </div>
      </div>
        {% if review.user == request.user %}
        <div>
            <a href="{% url 'review:review_modify' review.id %}"><span style="color:grey; font-size:24px;float:right; margin-right:10px; padding-bottom:9px;" class="material-icons-outlined">edit</span></a>
        </div>
        {% endif %}
    </div>
    <div style="text-align: center; margin-top:30px; height:200px;">
        <a href="{% url 'review:review_list' product.id %}"><button type="button" class="btn btn-outline-secondary">돌아가기</button></a>
    </div>
</div>


{% endblock %}

missions/week 5/back/templates/review/list.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}

<br>
<br>
<br>
    <div class="row" style="min-width:375px;">
        <!-- 상품 카테고리 시작 -->
        <div class="category_box">
            <ul class="nav nav-tabs" style="width:450px;">
              <li class="nav-item">
                <a href="/" class="nav-link">모든 상품</a>
              </li>
              {% for category in categories %}
              <li class="nav-item">
                <a href="{{category.get_absolute_url}}" class="nav-link {% if selected_category.slug == category.slug %}active{% endif %}">{{category.name}}</a>
              </li>
              {% endfor %}
            </ul>
        </div>
        <!-- 상품 카테고리 끝 -->

        <!-- 상품 세부 정보 시작  -->
        <div class="col-4" style="margin-top:5px;">
            {% if product.image.url == True %}
            <img src="{{product.image.url}}" width="375px;">
            {% else %}
            <img src="{{product.image_url}}" width="375px;">
            {% endif %}
        </div>
        <div class="col" style="width:375px; margin-top:25px; margin-left:25px;">
            <div style="display: flex; align-items: center; max-width:355px; margin-bottom:10px;">
                <span style="font-size:16px;color:#555555;">상품명</span>
                <span style="font-size:16px;color:#555555; margin-left:40px;">{{product.name}}</span>
            </div>
            <div style="display: flex; align-items: center; width:300px; margin-bottom:10px;">
                <span style="font-size:16px;color:#555555;">마켓</span>
                <span style="font-size:16px;color:#555555; margin-left:55px;">{{product.seller.market}}</span>
            </div>
            <div style="display: flex; align-items: center; width:300px; margin-bottom:20px;">
                <span style="font-size:16px;color:#555555;">판매가</span>
                <span style="font-size:16px;color:#555555; margin-left:40px;">{{product.price|intcomma}} KRW</span>
            </div>
            <div style="display: flex; align-items: center; width:355px; margin-bottom:10px;">
                <span style="font-size:16px;color:#555555; margin-bottom:10px;">소개</span>
                <span style="font-size:16px;color:#555555; margin-left:55px; margin-bottom:10px;">{{product.description}}</span>
            </div>
            <!-- 상품 세부 정보 끝 -->

            <!-- 옵션 선택, 장바구니 시작 -->
            <form action="{% url 'cart:add_cart' %}" method="POST">
            {% csrf_token %}
                <div style="display: flex; align-items: center; width:320px; margin-bottom:20px;">
                        <span style="font-size:16px;color:#555555;">옵션</span>
                        <select name="inventory" class="form-select" aria-label="Default select example" style="margin-left:20px; width:260px;">
                            {% for inventory in inventories %}
                                {% if inventory.stock == 0 %}
                                <option value="{{inventory.id}}">{{inventory.color}} - {{inventory.size}}  (품절)</option>
                                {% else %}
                                <option value="{{inventory.id}}">{{inventory.color}} - {{inventory.size}} ({{inventory.stock}}개 남음)</option>
                                {% endif %}
                            {% endfor %}
                        </select>

                </div>

            <!--   수량   -->
                <div id="mainDiv" style="display: flex; align-items: center; margin-bottom:25px; margin-top:20px; font-size:16px;color:#555555;">
                    수량 선택 <input type="number" name="quantity" style="width:70px; margin-left:20px;" min="1" id="numberPlace" class="form-control qty-input text-center">
                </div>
            <!--   수량  끝 -->

                <div>
                    <button type="submit" class="btn btn-outline-secondary" style="margin-right:5px;">Add To Cart</button>
            </form>
                <button type="button" class="btn btn-outline-secondary">To WishList</button>
            </div>
        </div>
        <!-- 옵션 선택, 장바구니 끝 -->

        <div style="display: flex; align-items: center;">
            <hr style="border:1px silver;width: 100%;">
        </div>

        <!--  상품 문의 시작    -->
        <div style="text-align:center;">
            <a href="{{product.get_absolute_url}}">
                <span style="font-size:16px;color:#555555; margin-right:25px; text-align:center;">상품 문의</span>
            </a>
            <span style="font-size:16px;color:black; margin-left:25px; margin-right:10px; text-align:center;">리뷰</span>
        </div>
        <div style="margin-left:3px; margin-top:10px;">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">No.</th>
                  <th scope="col">ID</th>
                  <th scope="col">리뷰 내용</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
              {% for review in page_obj.object_list %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ review.user.username }}</td>
                  <td><a href="{% url 'review:review_detail' review.id %}"><div class="word" style="width:80px;">{{ review.title }}</div></a></td>
                  <td><a href="{% url 'review:review_delete' review.id %}"><span class="material-icons-outlined" style="font-size:13px; color:grey; margin-right:10px;">close</span></a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        </div>
        <!--  상품 문의 끝  -->

        <!-- 페이징처리 시작 -->
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center"">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% for page_number in page_obj.paginator.page_range %}
                    {% if page_number == page_obj.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <!-- 페이징처리 끝 -->

        <!-- 문의 입력란 시작 -->
        <div style="text-align: center; height:200px; padding-right:50px;">
            <a href="{% url 'review:review_create' product.id %}"><button type="button" class="btn btn-outline-secondary" style="float:right;">리뷰쓰기</button></a>
        </div>
        <!-- 문의 입력란 끝 -->
    </div>

<script>
document.getElementById('numberPlace').value = '1';
</script>

{% endblock %}

missions/week 5/back/templates/review/modify.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}
<br>
<br>
<br>
<div class="row">
    <!--  장바구니 칸 시작  -->
    <div class="category_box" style="text-align:center;">
        <p style="padding-top:8px; padding-right:8px;"><b>리뷰 수정</b></p>
    </div>

    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div style="display:flex; margin-top:5px;">
            {% if product.image.url == True %}
            <a href="{{product.get_absolute_url}}"><img class="item_img" src="{{product.image.url}}"></a>
            {% else %}
            <a href="{{product.get_absolute_url}}"><img class="item_img" src="{{product.image_url}}"></a>
            {% endif %}
            <div style="margin-top:10px;">
                <div class="word" style ="padding-left:15px; width:220px; font-size:16px; color:gray;">
                    문의 상품: {{ product }}
                </div>
                <div style="font-size:16px; color:gray; padding-left:15px; padding-top:10px;">
                   가격: {{ product.price|intcomma }} KRW
                </div>
            </div>
        </div>
    </li>


    <!-- 리뷰 입력란 시작   -->
    <div style="margin-left:20px; margin-top:20px; margin-bottom:150px; width:320px;">
        <form action="{% url 'review:review_modify' review.id %}" method="POST">
        {% csrf_token %}
        <div class="mb-3" style="width:280px;">
          <label for="exampleFormControlInput1" class="form-label">제목</label>
          <input type="text" name='title' class="form-control" value="{{review.title}}" id="exampleFormControlInput1"">
        </div>
        <div class="mb-3" style="width:320px;">
          <label for="exampleFormControlTextarea1" class="form-label">리뷰 내용</label>
          <textarea name="body" style="height:250px;" class="form-control" id="exampleFormControlTextarea1" rows="3">{{review.comment}}</textarea>
        </div>
        <button type="submit" class="btn btn-outline-secondary" style="margin-top:15px; margin-left:125px;">수정하기</button>
        </form>
    </div>
    <!-- 리뷰 입력란 끝 -->
</div>
{% endblock %}

missions/week 5/back/templates/review/reviewbot.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}
<br>
<br>
<br>
<br>
<br>
        <!-- 셀러 등록란 -->
    <div style="text-align:center;">
        <p><b>리뷰봇 설정하기</b></p>
    </div>
        <div style="text-align: center; padding-left:50px; height:200px;">
            <form action="{% url 'review:review_bot' %}" method="POST">
            {% csrf_token %}
            {% if bot_status.use_bot %}
            <div class="input-group mb-3" style="margin-top:30px; width:300px; padding-right:15px;">
              <form action="" method="POST">
                    <div class="form-check">
                      <input class="form-check-input" value="1" name="choice" type="radio" id="flexRadioDefault1" checked>
                      <label class="form-check-label" for="flexRadioDefault1">
                        리뷰봇을 사용할게요.
                      </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" value="0" name="choice" type="radio" id="flexRadioDefault2">
                      <label class="form-check-label" for="flexRadioDefault2">
                        리뷰봇을 사용하지 않을게요.
                      </label>
                    </div>
            </div>
            {% else %}
            <div class="input-group mb-3" style="margin-top:30px; width:300px; padding-right:15px;">
              <form action="" method="POST">
                    <div class="form-check">
                      <input class="form-check-input" value="1" name="choice" type="radio" id="flexRadioDefault1">
                      <label class="form-check-label" for="flexRadioDefault1">
                        리뷰봇을 사용할게요.
                      </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" value="0" name="choice" type="radio" id="flexRadioDefault2" checked>
                      <label class="form-check-label" for="flexRadioDefault2">
                        리뷰봇을 사용하지 않을게요.
                      </label>
                    </div>
            </div>
            {% endif %}
                <button class="btn btn-outline-secondary" style="margin-left:150px;" type="submit" id="button-addon1">저장</button>

            </form>
        </div>
        <!-- 설러 등록란 끝 -->

{% endblock %}