missions/week 1/back/MBLY/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('malls.urls')),
    path('updatedb/', include('updatedb.urls')),
]

missions/week 1/back/ably/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.shortcuts import redirect

from contents.views import HomeView, ProductListView, ProductDetailView, SearchView, CategoryView, BrandView, CartView
from apis.views import KaKaoSignInView, KaKaoSignInCallBackView
from contents.pay_views import KaKaoPayLogic, KaKaoPayView, payFail, payCancel, PaySuccess


# NonUserTemplateView 를 사용하는 이유는 로그인과 회원가입 페이지에서 사용자의 접근을 막기위함
class NonUserTemplateView(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            return redirect('/')
        return super(NonUserTemplateView, self).dispatch(request, *args, **kwargs)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    # apis app urls.py connect
    path('apis/', include('apis.urls')),

    # product
    path('product/', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/category/<str:slug>/', CategoryView.as_view(), name='category_product_list'),
    path('product/brand/<str:slug>/', BrandView.as_view(), name='brand_product_list'),

    # cart
    path('cart/', CartView.as_view(), name='cart'),

    # search
    path('product/search/<str:q>/', SearchView.as_view(), name="search"),

    # user
    path('login/', NonUserTemplateView.as_view(template_name='user/login.html'), name='login'),
    path('register/', NonUserTemplateView.as_view(template_name='user/register.html'), name='register'),

    # kakao
    # path('user/login/kakao/', KaKaoSignInView.as_view(), name='kakao_login'),
    # path('user/login/kakao/callback/', KaKaoSignInCallBackView.as_view(), name='kakao_callback'),

    # 소셜로그인 관련 url
    # path('user/', include('allauth.urls')),
    path('social/', include('allauth.urls')),

    # 5주차
    # 카카오페이
    path('kakaoPay/', KaKaoPayView.as_view(), name='Pay'),
    path('kakaoPayLogic/', KaKaoPayLogic),
    path('payCancel/', payCancel),
    path('payFail/', payFail),
    path('paySuccsee/', PaySuccess),
]

missions/week 1/back/base/urls.py
from django.contrib import admin
from django.urls import path, include
from mutbly.views import index, RegisterView, LoginView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',index),
    path('admin/', admin.site.urls),
    path('register/', RegisterView.as_view()),
    # path('login/', LoginView.as_view()),
    path('mutbly/', include('mutbly.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/profile/', index)

]

missions/week 1/back/mbly/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('markets.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

missions/week 1/back/shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', shop_main, name='home'),
    path('category/<str:category_slug>', shop_main, name='product_in_category'),
    path('<int:product_id>/<product_slug>', product_detail, name='product_detail'),
    path('search', search, name='search'),
    path('question/<int:question_id>', question_delete, name="question_delete"),
]

missions/week 1/back/templates/shop/detail.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}
<br>
<br>
<br>
<br>
    <div class="row" style="margin-left:3px;">
        <!-- 상품 카테고리 시작 -->
        <div class="col-2" style="min-width:123px;">
            <div class="list-group" style="margin-left:3px;">
                <a href="/" class="list-group-item">모든 상품</a>
                {% for category in categories %}
                    <a href="{{category.get_absolute_url}}" class="list-group-item {% if selected_category.slug == category.slug %}active{% endif %}">{{category.name}}</a>
                {% endfor %}
            </div>
        </div>
        <!-- 상품 카테고리 끝 -->

        <!-- 상품 세부 정보 시작  -->
        <div class="col-4">
            <img src="{{product.image.url}}" width="380px;">
        </div>
        <div class="col" style="margin-top:25px; margin-left:35px;">
            <div style="display: flex; align-items: center; width:500px; margin-bottom:10px;">
                <span style="font-size:16px;color:#555555;">상품명</span>
                <span style="font-size:16px;color:#555555; margin-left:50px;">{{product.name}}</span>
            </div>
            <div style="display: flex; align-items: center; width:300px; margin-bottom:10px;">
                <span style="font-size:16px;color:#555555;">마켓</span>
                <span style="font-size:16px;color:#555555; margin-left:65px;">{{product.market}}</span>
            </div>
            <div style="display: flex; align-items: center; width:300px; margin-bottom:20px;">
                <span style="font-size:16px;color:#555555;">판매가</span>
                <span style="font-size:16px;color:#555555; margin-left:50px;">{{product.price|intcomma}} KRW</span>
            </div>
            <div style="display: flex; align-items: center; width:500px; margin-bottom:10px;">
                <span style="font-size:16px;color:#555555; margin-bottom:10px;">소개</span>
                <span style="font-size:16px;color:#555555; margin-left:65px; margin-bottom:10px;">{{product.description}}</span>
            </div>
            <!-- 상품 세부 정보 끝 -->

            <!-- 옵션 선택, 장바구니 시작 -->
            <div style="display: flex; align-items: center; width:300px; margin-bottom:20px;">
                <select class="form-select" aria-label="Default select example">
                  <option selected>옵션을 선택해주세요.</option>
                    {% for inventory in inventories %}
                        {% if inventory.stock == 0 %}
                        <option value="{{forloop.counter}}">{{inventory.color}} -- {{inventory.size}}  (품절)</option>
                        {% else %}
                        <option value="{{forloop.counter}}">{{inventory.color}} -- {{inventory.size}} ({{inventory.stock}}개 남음)</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>

            <div>
                <button type="button" class="btn btn-outline-secondary" style="margin-right:5px;">Add To Cart</button>
                <button type="button" class="btn btn-outline-secondary">To WishList</button>
            </div>
        </div>
        <!-- 옵션 선택, 장바구니 끝 -->

        <div style="display: flex; align-items: center;">
            <hr style="border:1px silver;width: 100%;">
        </div>

        <!--  상품 문의 시작    -->
        <span style="font-size:16px;color:#555555; text-align:center;">상품 문의</span>
        <div style="margin-left:50px;">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">No.</th>
                  <th scope="col">ID</th>
                  <th scope="col">문의 내용</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
              {% for question in page_obj.object_list %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ question.user.username }}</td>
                  <td>{{ question.comment }}</td>
                  <td><a href="{% url 'shop:question_delete' question.id %}"><span class="material-icons-outlined" style="font-size:13px; color:grey;">close</span></td></a>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        </div>
        <!--  상품 문의 끝  -->

        <!-- 페이징처리 시작 -->
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center"">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% for page_number in page_obj.paginator.page_range %}
                    {% if page_number == page_obj.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <!-- 페이징처리 끝 -->

        <!-- 문의 입력란 시작 -->
        <div style="margin-left:50px;">
            <form action="" method="POST">
            {% csrf_token %}
            <div class="input-group mb-3" style="margin-left:120px; width:800px;">
              <form action="" method="POST">
                  <input type="text" name="body" class="form-control" placeholder="문의 내용을 입력해주세요." aria-label="문의 내용을 입력해주세요." aria-describedby="button-addon2">
                  <button class="btn btn-outline-secondary" type="submit" id="button-addon1">등록</button>
            </div>
            </form>
        </div>
        <!-- 문의 입력란 끝 -->
    </div>
{% endblock %}

missions/week 1/back/templates/shop/main.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}

<br>
<br>
<br>

<div class="row" style="margin-left:3px;">
    <!--  카테고리 선택 시작  -->
    <div class="col-2" style="min-width:123px; max-width:200px; position: fixed;">
        <br>
        <div class="list-group">
            <a href="/" class="list-group-item {% if not selected_category %}active{% endif %}">모든 상품</a>
            {% for category in categories %}
                <a href="{{category.get_absolute_url}}" class="list-group-item {% if selected_category.slug == category.slug %}active{% endif %}">{{category.name}}</a>
            {% endfor %}
        </div>
    </div>
    <!--  카테고리 선택 끝  -->

    <div class="col" style="margin-left: 230px;">
        <div class="alert alert-light" role="alert">
            {% if selected_category %}
                {{selected_category.name}}
            {% else %}
                모든 상품
            {% endif %}
        </div>

        <!--  상품 박스 시작  -->
        {% for product in page_obj.object_list %}
            <div class="col-4" style="float:left; width:250px; margin:20px;">
                <div class="item_body">
                    <div class="item_box">
                        <a href="{{product.get_absolute_url}}"><img class="item_img" src="{{product.image.url}}"></a>
                        <div class="item_first_row">
                            <div class="price_tag">
                                <b>{{product.price|intcomma}}</b>
                            </div>
                            <div class="item_icon">
                                <span class="favorite_icon material-icons-outlined icons" style="color: red;" >
                                        favorite_border
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="item_second_row">
                        <b>{{product.market}}</b>
                    </div>
                    <div class="item_third_row">
                        {{product.name}}
                    </div>
                </div>
            </div>
        {% endfor %}
        <!--  상품 박스 끝 -->
    </div>
</div>

<!-- 페이징처리 시작 -->
<nav aria-label="Page navigation example" style="margin-top:200px;">
    <ul class="pagination justify-content-center"">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        {% for page_number in page_obj.paginator.page_range %}
            {% if page_number == page_obj.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
<!-- 페이징처리 끝 -->
{% endblock %}

missions/week 1/back/templates/shop/search.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}

<br>
<br>
<div class="row" style="margin-left:3px;">
    {% if not products %}
    <div class="alert alert-info" role="alert">
    <h4 style="margin-left:30px; padding-top:10px;">검색 결과가 없습니다. 😅 </h4>
    </div>
    <!-- 상품 카테고리 시작 -->
    <div class="col-2" style="min-width:123px;">
        <div class="list-group" style="margin-left:3px;">
            <a href="/" class="list-group-item">모든 상품</a>
            {% for category in categories %}
                <a href="{{category.get_absolute_url}}" class="list-group-item {% if selected_category.slug == category.slug %}active{% endif %}">{{category.name}}</a>
            {% endfor %}
        </div>
    </div>
    <!-- 상품 카테고리 끝 -->
    {% else %}
    <div class="alert alert-info" role="alert">
    '{{q}}'에 대한 검색 결과 입니다.
    </div>
    <!-- 상품 카테고리 시작 -->
    <div class="col-2" style="min-width:123px;">
        <div class="list-group" style="margin-left:3px;">
            <a href="/" class="list-group-item">모든 상품</a>
            {% for category in categories %}
                <a href="{{category.get_absolute_url}}" class="list-group-item {% if selected_category.slug == category.slug %}active{% endif %}">{{category.name}}</a>
            {% endfor %}
        </div>
    </div>
    <!-- 상품 카테고리 끝 -->

    <!--  상품 박스 시작  -->
    {% for product in products %}
        <div class="col-4" style="float:left; width:250px; margin:20px;">
            <div class="item_body">
                <div class="item_box">
                    <a href="{{product.get_absolute_url}}"><img class="item_img" src="{{product.image.url}}"></a>
                    <div class="item_first_row">
                        <div class="price_tag">
                            <b>{{product.price|intcomma}}</b>
                        </div>
                        <div class="item_icon">
                            <span class="favorite_icon material-icons-outlined icons" style="color: red;" >
                                    favorite_border
                            </span>
                        </div>
                    </div>
                    <div class="item_second_row">
                        <b>{{product.market}}</b>
                    </div>
                    <div class="item_third_row">
                        {{product.name}}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <!--  상품 박스 끝  -->
    {% endif %}
</div>
{% endblock %}